# Generated by Django 2.2.6 on 2019-10-31 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='you@getsome.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='first_name',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='phoneNumber',
            field=models.CharField(default='123456789', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(default='GA', max_length=2),
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zipCode',
            field=models.CharField(default='12345', max_length=5),
        ),
    ]
